import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="text-lg sm:text-2xl font-medium absolute left-0 top-0 leading-none tracking-tight text-gray-900 p-4">
          <code>[DICK]</code> ― by J&J
        </p>
        <header className="container pt-20 px-4">
            <h1 className="text-4xl sm:text-6xl lg:text-7xl leading-none font-extrabold tracking-tight text-gray-900 mt-10 mb-8 sm:mt-14 sm:mb-10">
              CryptoDicks
            </h1>
            <p className="text-lg sm:text-2xl sm:leading-10 font-medium mb-4">
                A NFT collection generated programmatically.
            </p>
            <ul className="text-lg sm:text-2xl sm:leading-10 font-medium mb-16">
              <li>
                  ✅ Full on-chain metadata (avoid power cheating).
              </li>
              <li>
                  ✅ Decentralized storage (avoid censure).
              </li>
              <li>
                  ✅ Rarity algorithm (like in the real-world).
              </li>
              <li>
                  ✅ Vectorized images (high quality in all sizes).
              </li>
            </ul>

            <code className="text-lg sm:text-2xl font-medium">
                Quantity: <code>
                    <span id="quantity">0</span>
                    / 10K (<span id="quantity_percent">0</span>%)
                    <span> | Possible combinations: </span>
                    <span id="capacity">0</span>
                </code>
            </code>
        </header>
      </main>
    </>
  )
}

export default Home
